name: First Workflow

on:
  push: # This is the trigger
    branches: # Below I can list on which branches I need these actions to apply
      - main

jobs:
  example-job: # this the name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first Github Actions Workflow!"

      - name: Checkout Repository # Checkout means I need to clone the repository
        uses: actions/checkout@v6.1.0

      - name: List Directory
        run: ls -la
